name: Build
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      APP_NAME: api-xamlple
      RELEASE_REGISTRY: ruca93
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Docker Login to Release registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get parent commit SHA
        id: parent
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD^)"

      - name: Docker build and push main
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          no-cache: true
          push: true
          tags: ${{ env.RELEASE_REGISTRY }}/api-xample:${{ steps.parent.outputs.sha }}
          platform: linux/amd64

  # deploy-dev:
  #   name: Deploy dev
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: terraform plan
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS__ECS_DEPLOY_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS__ECS_DEPLOY_SECRET_ACCESS_KEY }}
  #       uses: dflook/terraform-plan@v1.34.0
  #       with:
  #         path: ./terraform
  #         workspace: dev
  #         var_file: ./terraform/dev.tfvars
  #         variables: |
  #           ServiceVersion="${{ github.sha }}"
      
  #     - name: terraform apply
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS__ECS_DEPLOY_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS__ECS_DEPLOY_SECRET_ACCESS_KEY }}
  #       uses: dflook/terraform-apply@v1.34.0
  #       with:
  #         path: ./terraform
  #         workspace: dev
  #         var_file: ./terraform/dev.tfvars
  #         variables: |
  #           ServiceVersion="${{ github.sha }}"
  #         auto_approve: true